config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'signup'  => 'users#new'
  root 'homes#index'
  get 'admin' => 'admin/dashboards#index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'holiday' => 'holidays#index'
  namespace :admin do
    resources :dashboards
    resources :holidays
    resources :users
    get 'applied_leaves' => 'dashboard#applied_leaves'
    resources :emails
  end

  resources :users ,only: [:show, :new, :create, :edit, :update, :index] do
    resources :leaveemps
    get 'upcoming_leaves' => 'leaveemps#upcoming_leaves'
    get 'leave_history' => 'leaveemps#leave_history'
  end

  resources :roles
  resources :admin

  get 'users/add_manager'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout "admin"
  before_action :logged_in_admin
  def index

  end

  def applied_leaves
    @leaves = Leaveemp.where("startdate > ?", Time.zone.now.to_date).order(:startdate)
  end

  def logged_in_admin
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  before_action :check_log_in
  layout "admin"
  #before_action :authorize_admins , only: [:index]
  def index
    @user = User.find(current_user.id)
    @name = @user.name
  end
  def check_log_in
    if current_user.nil?
      redirect_to login_path
    end
  end
  def authorize_admins
    unless current_user.admin?
      redirect_to root_path
    end
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/views/admin/dashboard/applied_leaves.html.erb
<% if @leaves.blank? %>
  <p>No Applies Leaves</p>
<% else %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Leave Schedule</th>
        <th scope="col">Comment</th>
        <th scope="col">Action</th>
      </tr>
    </thead>

    <% @leaves.each do |leave_val| %>
      <tbody>
        <tr>
          <td>
            Start Date: <%= leave_val.startdate %><br>
            End Date: <%= leave_val.enddate %><br>
            Number of Days: <%= ((leave_val.enddate - leave_val.startdate).to_i + 1) %>
          </td>
          <td>
            <% if leave_val.comment.blank? %>
              --
            <% else %>
              <%= leave_val.comment %>
            <% end %>
          </td>
          <td>
            <%= link_to 'Edit', edit_user_leaveemp_path(current_user, leave_val) %>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
<% end %>